# This is just a temporary template - we will delete this once we move preview to stable
name: Parity Report
description: "Use this issue to report that a regression occurred in the transition between gpui-1 Zed and gpui-2 Zed"
labels: ["admin read", "triage", "enhancement", "defect", "parity"]
body:
    - type: checkboxes
      attributes:
          label: Check for existing issues
          description: Check the backlog of issues to reduce the chances of creating duplicates; if an issue already exists, place a `+1` (👍) on it.
          options:
              - label: Completed
                required: true
    - type: textarea
      attributes:
          label: Describe the feature that was lost
      validations:
          required: true
    - type: textarea
      attributes:
          label: |
              If necessary, add screenshots of gpui-1 Zed to show the missing feature
          description: Drag images into the text input below
      validations:
          required: false
